version : "3"

services:
        db:
            image: mysql:latest
            environment:
                MYSQL_DATABASE: lamp_docker
                MYSQL_USER: lamp_docker
                MYSQL_PASSWORD: password
                MYSQL_ALLOW_EMPTY_PASSWORD: 1
                
        wwww:
              depends_on:
                  - db
             
              build:
                   context: .
                   dockerfile: Dockerfile
              volumes:      #volume is connecting folder on local to folder on container
                  - "./:/var/www/html"
              ports:
                  - 8004:80
                  - 443:443

        phpmyadmin:
                  depends_on:
                      - db
                  image: phpmyadmin/phpmyadmin
                  ports:
                    - 8001:80
                  environment:
                    - PMA_HOST=db
                    - PMA_PORT=3306
